allowBuilds:
  '@playwright/browser-chromium': false
  '@playwright/browser-firefox': false
  '@playwright/browser-webkit': false
  esbuild: false
  keytar: false
  protobufjs: false
  puppeteer: false
  sharp: false
