name: Documentation Checks

on:
  pull_request:
    branches:
      - main

jobs:
  mint-checks:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install Mint CLI
        run: npm install -g mint
        
      - name: Run Broken Links Check
        run: mint broken-links 
      
      - name: Run OpenAPI Schema Check
        run: mint openapi-check https://api.comfy.org/openapi
        
