name: Link Validation

on:
  pull_request:
    paths:
      - '**/*.mdx'
      - '**/*.md'
  push:
    branches: [main]
    paths:
      - '**/*.mdx'
      - '**/*.md'

jobs:
  validate-links:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Run link validation
        run: python .github/scripts/validate-links.py

      - name: Comment PR (if validation fails)
        if: failure() && github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            try {
              const errors = fs.readFileSync('/tmp/link-errors.txt', 'utf8');
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: `## Link Validation Failed\n\n${errors}`
              });
            } catch (error) {
              console.log('No error file found');
            }